-- Phase 09: HLS ladder generated by the worker. Null = no HLS (videos processed before this
-- phase keep playing through the progressive /stream fallback; no backfill — reprocessing is a
-- manual ops action).

ALTER TABLE videos
    ADD COLUMN hls_master_key varchar(500);
